module.exports = {
    TB_CANCEL_REASON: 'tb_cancel_reason',
    TB_CHANGE_REASON: 'tb_change_reason',
    TB_COMPANY: 'tb_company',
    TB_DOC_TYPE: 'tb_doc_type',
    TB_DRIVER: 'tb_driver',
    TB_GRADE: 'tb_grade',
    TB_HOLIDAY: 'tb_holiday',
    TB_OWNER_TYPE: 'tb_owner_type',
    TB_PDPA: 'tb_pdpa',
    TB_PDPA_CONCENT: 'tb_pdpa_concent',
    TB_PDPA_TYPE: 'tb_pdpa_type',
    TB_PL: 'tb_pl',
    TB_PL_DETAIL: 'tb_pl_detail',
    TB_PROVINCE: 'tb_province',
    TB_RET: 'tb_ret',
    TB_SCHEDULE: 'tb_schedule',
    TB_SCHEDULE_WK: 'tb_schedule_wk',
    TB_SETTING: 'tb_setting',
    TB_SHIPMENT_STATUS: 'tb_shipment_status',
    TB_TRD: 'tb_trd',
    TB_TRD_CONFIRM: 'tb_trd_confirm',
    TB_TRUCK: 'tb_truck',
    TB_TRUCK_TYPE: 'tb_truck_type',
  }